[workspace]
resolver = "2"

members = [
    "dnstp",
    "dnstp-client",
    "dnstp-server",
]

[workspace.package]
version = "0.1.2"
authors = ["sarsoo <andy@sarsoo.xyz>"]
documentation = "https://sarsoo.github.io/dnstp"